sudo: required
services:
  - docker

before_install:
  - docker build -t nklein/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run nklein/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-799371115323"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

after_success:
  - docker build -t nklein/multi-client ./client
  - docker build -t nklein/multi-nginx ./nginx
  - docker build -t nklein/multi-server ./server
  - docker build -t nklein/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

  # Take those images and push them to docker hub
  - docker push nklein/multi-client
  - docker push nklein/multi-nginx
  - docker push nklein/multi-server
  - docker push nklein/multi-worker
